Attempt to fix dependency error that occurs in CI tests (though not locally).
It's related to a chempy import in DataRepo.models.utilities: `from chempy import Substance`.  It produces the following error from quantities/uncertainquantity.py when it tried to call `np.array(other, copy=False, subok=True)`:

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

Files checked in: requirements/common.txt